### ISSUE TITLE
Error: Cannot find module 'serialport'

### ISSUE THREAD

**Issue by hashimK** [andySigler/NodeJS_Yun_Example#1]
Hello sir,
I carefully followed your tutorial of setting node.js on Yun. But, I'm getting this error "Error: Cannot find module 'serialport' " when I try to run the app.js file situated in mnt/sda1/arduino/node folder. Please help hoe to overcome this error.
Thank you.

**Comment by andySigler** [comment]
thank you for the issue. I found that the link to my tutorial was broken, so I just updated it: https://github.com/andySigler/NodeJS_Yun_Example/commit/2b10dbb0b2e43c6b642fb319b1317b9d50920615

Have you install `node-serialport` as the tutorial describes?

http://andysigler.com/teaching/nodejs-arduino-yun/

**Comment by hashimK** [comment]
Yes I have installed node-serialport.
When i again do "opkg install node-serialport" it shows:
Package node-serialport (2.0.6-1) installed in root is up to date.

**Comment by hashimK** [comment]
Hello,
I solved the problem by following these steps:

- Make a folder node_modules in mnt/sda1/

- cd /mnt/sda1

- wget http://wiki.linino.org/lib/exe/fetch.php?media=wiki:serialport-1.6.1_mips-25-ubuntu.tar.gz -O serialport-1.6.1_mips-25-ubuntu.tar.gz

-  run $ tar xvf serialport-1.6.1_mips-25-ubuntu.tar.gz -C /mnt/sda1/node_modules

Thanks Anyways
